apiVersion: apps/v1
kind: Deployment
metadata:
  name: ask
  labels:
    app: ask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ask
  template:
    metadata:
      labels:
        app: ask
    spec:
      containers:
        - name: ask
          image: username/ask:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5